### ISSUE TITLE
Undefined method `empty?' for 200:Integer

### ISSUE THREAD

**Issue by mikeantonelli** [stackify/stackify-api-ruby#21]
The logger_proxy appears to assume that `msg` is going to be an object that responds to `empty?`: https://github.com/stackify/stackify-api-ruby/blob/c1fd6a2346a6e6191695044362959dc294fdea39/lib/stackify/logger_proxy.rb#L9

Presumably you could update to:

```ruby
-> (msg, caller) { Stackify.logger_client.log(level.downcase, msg, caller) unless msg.respond_to(:empty?) && msg.empty? }
```

https://apidock.com/ruby/Object/respond_to%3F

or maybe force it to a string:

```ruby
-> (msg, caller) { Stackify.logger_client.log(level.downcase, msg, caller) unless msg.to_s.empty? }
```

Here is an error we encountered when a http client was logging its response code:
```sh
undefined method `empty?' for 200:Integer
/home/app/webapp/vendor/bundle/ruby/2.6.0/gems/stackify-api-ruby-1.0.13/lib/stackify/logger_proxy.rb:9:in `block (2 levels) in initialize'
/home/app/webapp/vendor/bundle/ruby/2.6.0/gems/stackify-api-ruby-1.0.13/lib/stackify/logger_proxy.rb:16:in `block (3 levels) in initialize'
/home/app/webapp/vendor/bundle/ruby/2.6.0/gems/google-api-client-0.29.1/lib/google/apis/core/http_command.rb:308:in `execute_once'
/home/app/webapp/vendor/bundle/ruby/2.6.0/gems/google-api-client-0.29.1/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
...
```

**Comment by darinhoward** [comment]
This has been fixed in 1.0.14 - https://rubygems.org/gems/stackify-api-ruby/versions/1.0.14
